<?php

use App\Models\User\FrontendUsersSpecificInfo;
use Illuminate\Database\Seeder;

/**
 * Class FrontendUsersSpecificInfoSeeder
 */
class FrontendUsersSpecificInfoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        FrontendUsersSpecificInfo::insert(
            [
             [
              'id'            => 1,
              'user_id'       => 1,
              'level'         => 2,
              'nickname'      => 'harriszhongdai',
              'experience'    => 2500,
              'avatar'        => 1,
              'email'         => '1823444@qq.com',
              'zip_code'      => '233333',
              'address'       => '朝歌',
              'register_type' => 0,
              'total_members' => 3,
              'domain'        => null,
              'g_active'      => '{"IM": 0, "KY": 1, "VR": 1}',
              'created_at'    => null,
              'updated_at'    => null,
             ],
             [
              'id'            => 2,
              'user_id'       => 2,
              'level'         => 1,
              'nickname'      => '亚索Suo',
              'experience'    => 1500,
              'avatar'        => 1,
              'email'         => 'sunshine@gmail.com',
              'zip_code'      => '1600',
              'address'       => 'State of California',
              'register_type' => 0,
              'total_members' => 3,
              'domain'        => null,
              'g_active'      => '{"IM": 1, "KY": 1, "VR": 1}',
              'created_at'    => null,
              'updated_at'    => '2020-05-23 20:28:32',
             ],
             [
              'id'            => 3,
              'user_id'       => 3,
              'level'         => 0,
              'nickname'      => '李青Lee',
              'experience'    => 500,
              'avatar'        => 1,
              'email'         => 'test@qq.com',
              'zip_code'      => '233333',
              'address'       => 'test city',
              'register_type' => 0,
              'total_members' => 3,
              'domain'        => null,
              'g_active'      => null,
              'created_at'    => null,
              'updated_at'    => null,
             ],
             [
              'id'            => 4,
              'user_id'       => 4,
              'level'         => 0,
              'nickname'      => null,
              'experience'    => 0,
              'avatar'        => 9,
              'email'         => null,
              'zip_code'      => null,
              'address'       => null,
              'register_type' => 0,
              'total_members' => 0,
              'domain'        => null,
              'g_active'      => null,
              'created_at'    => '2020-05-23 20:40:50',
              'updated_at'    => '2020-05-23 20:40:50',
             ],
             [
              'id'            => 5,
              'user_id'       => 5,
              'level'         => 0,
              'nickname'      => null,
              'experience'    => 0,
              'avatar'        => 14,
              'email'         => null,
              'zip_code'      => null,
              'address'       => null,
              'register_type' => 0,
              'total_members' => 0,
              'domain'        => null,
              'g_active'      => null,
              'created_at'    => '2020-05-23 20:46:56',
              'updated_at'    => '2020-05-23 20:46:56',
             ],
             [
              'id'            => 6,
              'user_id'       => 6,
              'level'         => 0,
              'nickname'      => null,
              'experience'    => 0,
              'avatar'        => 15,
              'email'         => null,
              'zip_code'      => null,
              'address'       => null,
              'register_type' => 0,
              'total_members' => 0,
              'domain'        => null,
              'g_active'      => null,
              'created_at'    => '2020-05-23 20:48:09',
              'updated_at'    => '2020-05-23 20:48:09',
             ],
             [
              'id'            => 7,
              'user_id'       => 7,
              'level'         => 0,
              'nickname'      => null,
              'experience'    => 0,
              'avatar'        => 2,
              'email'         => null,
              'zip_code'      => null,
              'address'       => null,
              'register_type' => 0,
              'total_members' => 0,
              'domain'        => null,
              'g_active'      => null,
              'created_at'    => '2020-05-23 20:48:33',
              'updated_at'    => '2020-05-23 20:48:33',
             ],
             [
              'id'            => 8,
              'user_id'       => 8,
              'level'         => 0,
              'nickname'      => '地瑕在',
              'experience'    => 0,
              'avatar'        => 7,
              'email'         => null,
              'zip_code'      => null,
              'address'       => null,
              'register_type' => 0,
              'total_members' => 0,
              'domain'        => null,
              'g_active'      => '{"VR": 1}',
              'created_at'    => '2020-05-23 20:53:33',
              'updated_at'    => '2020-05-23 21:48:45',
             ],
            ],
        );
    }
}
