<?php

use App\Models\User\FrontendUsersAccountsReport;
use Illuminate\Database\Seeder;

/**
 * Class FrontendUsersAccountsReportSeeder
 */
class FrontendUsersAccountsReportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        FrontendUsersAccountsReport::insert(
            [
             [
              'id'                    => 1,
              'serial_number'         => 'JHHY55ae5f1e514a',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'game_thier_bet',
              'type_name'             => '游戏三方单一转出',
              'params_value_id'       => null,
              'in_out'                => 2,
              'before_balance'        => '30000.0000',
              'balance'               => '29990.0000',
              'before_frozen_balance' => '44440.0000',
              'frozen_balance'        => '44450.0000',
              'amount'                => '10.0000',
              'frozen_type'           => 1,
              'process_time'          => 1588948323,
              'params'                => '{"project_id":8,"game_vendor_id":2,"game_type_id":5}',
              'desc'                  => '0',
              'created_at'            => '2020-05-08 22:32:03',
              'updated_at'            => '2020-05-08 22:32:03',
             ],
             [
              'id'                    => 2,
              'serial_number'         => 'JHHY948516c87112',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'game_thier_bet',
              'type_name'             => '游戏三方单一转出',
              'params_value_id'       => null,
              'in_out'                => 2,
              'before_balance'        => '29990.0000',
              'balance'               => '29980.0000',
              'before_frozen_balance' => '44450.0000',
              'frozen_balance'        => '44460.0000',
              'amount'                => '10.0000',
              'frozen_type'           => 1,
              'process_time'          => 1588948330,
              'params'                => '{"project_id":9,"game_vendor_id":2,"game_type_id":5}',
              'desc'                  => '0',
              'created_at'            => '2020-05-08 22:32:10',
              'updated_at'            => '2020-05-08 22:32:10',
             ],
             [
              'id'                    => 3,
              'serial_number'         => 'JHHY4ac2e03dee4e',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'game_thier_bet',
              'type_name'             => '游戏三方单一转出',
              'params_value_id'       => null,
              'in_out'                => 2,
              'before_balance'        => '29980.0000',
              'balance'               => '29930.0000',
              'before_frozen_balance' => '44460.0000',
              'frozen_balance'        => '44510.0000',
              'amount'                => '50.0000',
              'frozen_type'           => 1,
              'process_time'          => 1588948342,
              'params'                => '{"project_id":10,"game_vendor_id":2,"game_type_id":5}',
              'desc'                  => '0',
              'created_at'            => '2020-05-08 22:32:22',
              'updated_at'            => '2020-05-08 22:32:22',
             ],
             [
              'id'                    => 4,
              'serial_number'         => 'JHHY8f3d33e3aa03',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'game_thier_bet',
              'type_name'             => '游戏三方单一转出',
              'params_value_id'       => null,
              'in_out'                => 2,
              'before_balance'        => '29930.0000',
              'balance'               => '29830.0000',
              'before_frozen_balance' => '44510.0000',
              'frozen_balance'        => '44610.0000',
              'amount'                => '100.0000',
              'frozen_type'           => 1,
              'process_time'          => 1588948352,
              'params'                => '{"project_id":11,"game_vendor_id":2,"game_type_id":5}',
              'desc'                  => '0',
              'created_at'            => '2020-05-08 22:32:32',
              'updated_at'            => '2020-05-08 22:32:32',
             ],
             [
              'id'                    => 5,
              'serial_number'         => 'JHHY97c72eb76af1',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'game_thier_bet',
              'type_name'             => '游戏三方单一转出',
              'params_value_id'       => null,
              'in_out'                => 2,
              'before_balance'        => '29830.0000',
              'balance'               => '29829.0000',
              'before_frozen_balance' => '44610.0000',
              'frozen_balance'        => '44611.0000',
              'amount'                => '1.0000',
              'frozen_type'           => 1,
              'process_time'          => 1588948366,
              'params'                => '{"project_id":12,"game_vendor_id":2,"game_type_id":5}',
              'desc'                  => '0',
              'created_at'            => '2020-05-08 22:32:46',
              'updated_at'            => '2020-05-08 22:32:46',
             ],
             [
              'id'                    => 6,
              'serial_number'         => 'JHHY1de3afab7830',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'game_thier_gain',
              'type_name'             => '游戏三方单一套现',
              'params_value_id'       => null,
              'in_out'                => 1,
              'before_balance'        => '29829.0000',
              'balance'               => '29833.0000',
              'before_frozen_balance' => '44611.0000',
              'frozen_balance'        => '44601.0000',
              'amount'                => '4.0000',
              'frozen_type'           => 3,
              'process_time'          => 1588952580,
              'params'                => '{"project_id":1,"game_vendor_id":2,"game_type_id":5,"unfreeze_amount":"10.0000"}',
              'desc'                  => '0',
              'created_at'            => '2020-05-08 23:43:00',
              'updated_at'            => '2020-05-08 23:43:00',
             ],
             [
              'id'                    => 7,
              'serial_number'         => 'JHHYd277dc01a451',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'game_thier_gain',
              'type_name'             => '游戏三方单一套现',
              'params_value_id'       => null,
              'in_out'                => 1,
              'before_balance'        => '29833.0000',
              'balance'               => '29840.0000',
              'before_frozen_balance' => '44601.0000',
              'frozen_balance'        => '44591.0000',
              'amount'                => '7.0000',
              'frozen_type'           => 3,
              'process_time'          => 1588952580,
              'params'                => '{"project_id":2,"game_vendor_id":2,"game_type_id":5,"unfreeze_amount":"10.0000"}',
              'desc'                  => '0',
              'created_at'            => '2020-05-08 23:43:00',
              'updated_at'            => '2020-05-08 23:43:00',
             ],
             [
              'id'                    => 8,
              'serial_number'         => 'JHHY066bf14f23d0',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'game_thier_gain',
              'type_name'             => '游戏三方单一套现',
              'params_value_id'       => null,
              'in_out'                => 1,
              'before_balance'        => '29840.0000',
              'balance'               => '29875.0000',
              'before_frozen_balance' => '44591.0000',
              'frozen_balance'        => '44541.0000',
              'amount'                => '35.0000',
              'frozen_type'           => 3,
              'process_time'          => 1588952580,
              'params'                => '{"project_id":3,"game_vendor_id":2,"game_type_id":5,"unfreeze_amount":"50.0000"}',
              'desc'                  => '0',
              'created_at'            => '2020-05-08 23:43:00',
              'updated_at'            => '2020-05-08 23:43:00',
             ],
             [
              'id'                    => 9,
              'serial_number'         => 'JHHY12cf1a5851d9',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'game_thier_gain',
              'type_name'             => '游戏三方单一套现',
              'params_value_id'       => null,
              'in_out'                => 1,
              'before_balance'        => '29875.0000',
              'balance'               => '29955.0000',
              'before_frozen_balance' => '44541.0000',
              'frozen_balance'        => '44441.0000',
              'amount'                => '80.0000',
              'frozen_type'           => 3,
              'process_time'          => 1588952580,
              'params'                => '{"project_id":4,"game_vendor_id":2,"game_type_id":5,"unfreeze_amount":"100.0000"}',
              'desc'                  => '0',
              'created_at'            => '2020-05-08 23:43:00',
              'updated_at'            => '2020-05-08 23:43:00',
             ],
             [
              'id'                    => 10,
              'serial_number'         => 'JHHY4bf831f893ed',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'withdraw_frozen',
              'type_name'             => '提现冻结',
              'params_value_id'       => null,
              'in_out'                => 2,
              'before_balance'        => '29955.0000',
              'balance'               => '28455.0000',
              'before_frozen_balance' => '44441.0000',
              'frozen_balance'        => '45941.0000',
              'amount'                => '1500.0000',
              'frozen_type'           => 1,
              'process_time'          => 1590239780,
              'params'                => '[]',
              'desc'                  => '0',
              'created_at'            => '2020-05-23 21:16:20',
              'updated_at'            => '2020-05-23 21:16:20',
             ],
             [
              'id'                    => 11,
              'serial_number'         => 'JHHY51912945b2e3',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'withdraw_frozen',
              'type_name'             => '提现冻结',
              'params_value_id'       => null,
              'in_out'                => 2,
              'before_balance'        => '28455.0000',
              'balance'               => '26955.0000',
              'before_frozen_balance' => '45941.0000',
              'frozen_balance'        => '47441.0000',
              'amount'                => '1500.0000',
              'frozen_type'           => 1,
              'process_time'          => 1590239800,
              'params'                => '[]',
              'desc'                  => '0',
              'created_at'            => '2020-05-23 21:16:40',
              'updated_at'            => '2020-05-23 21:16:40',
             ],
             [
              'id'                    => 12,
              'serial_number'         => 'JHHYd36e18578073',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'withdraw_frozen',
              'type_name'             => '提现冻结',
              'params_value_id'       => null,
              'in_out'                => 2,
              'before_balance'        => '26955.0000',
              'balance'               => '25455.0000',
              'before_frozen_balance' => '47441.0000',
              'frozen_balance'        => '48941.0000',
              'amount'                => '1500.0000',
              'frozen_type'           => 1,
              'process_time'          => 1590239805,
              'params'                => '[]',
              'desc'                  => '0',
              'created_at'            => '2020-05-23 21:16:45',
              'updated_at'            => '2020-05-23 21:16:45',
             ],
             [
              'id'                    => 13,
              'serial_number'         => 'JHHY669adad96b73',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'withdraw_frozen',
              'type_name'             => '提现冻结',
              'params_value_id'       => null,
              'in_out'                => 2,
              'before_balance'        => '25455.0000',
              'balance'               => '23955.0000',
              'before_frozen_balance' => '48941.0000',
              'frozen_balance'        => '50441.0000',
              'amount'                => '1500.0000',
              'frozen_type'           => 1,
              'process_time'          => 1590239809,
              'params'                => '[]',
              'desc'                  => '0',
              'created_at'            => '2020-05-23 21:16:49',
              'updated_at'            => '2020-05-23 21:16:49',
             ],
             [
              'id'                    => 14,
              'serial_number'         => 'JHHY27b9fca79f33',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'withdraw_frozen',
              'type_name'             => '提现冻结',
              'params_value_id'       => null,
              'in_out'                => 2,
              'before_balance'        => '23955.0000',
              'balance'               => '15067.0000',
              'before_frozen_balance' => '50441.0000',
              'frozen_balance'        => '59329.0000',
              'amount'                => '8888.0000',
              'frozen_type'           => 1,
              'process_time'          => 1590239902,
              'params'                => '[]',
              'desc'                  => '0',
              'created_at'            => '2020-05-23 21:18:22',
              'updated_at'            => '2020-05-23 21:18:22',
             ],
             [
              'id'                    => 20,
              'serial_number'         => 'JHHY1f0e46ac32c5',
              'platform_sign'         => 'JHHY',
              'top_id'                => 0,
              'parent_id'             => 0,
              'user_id'               => 2,
              'username'              => '亚索Suo',
              'type_sign'             => 'withdraw_finish',
              'type_name'             => '提现成功',
              'params_value_id'       => null,
              'in_out'                => 2,
              'before_balance'        => '15067.0000',
              'balance'               => '15067.0000',
              'before_frozen_balance' => '59329.0000',
              'frozen_balance'        => '50441.0000',
              'amount'                => '8888.0000',
              'frozen_type'           => 4,
              'process_time'          => 1590381158,
              'params'                => '[]',
              'desc'                  => '0',
              'created_at'            => '2020-05-25 12:32:38',
              'updated_at'            => '2020-05-25 12:32:38',
             ],
            ],
        );
    }
}
