<?php

use App\Models\DeveloperUsage\Menu\MerchantSystemMenu;
use Illuminate\Database\Seeder;

/**
 * Class MerchantSystemMenuSeeder
 */
class MerchantSystemMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        MerchantSystemMenu::insert(
            [
             [
              'id'      => 1,
              'label'   => '首页',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'icon'    => 'iconhome',
              'display' => 1,
              'level'   => 1,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 2,
              'label'   => '首页',
              'en_name' => 'Home',
              'route'   => '/home/home',
              'pid'     => 1,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 3,
              'label'   => '会员管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'icon'    => 'iconaccount',
              'display' => 1,
              'level'   => 1,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 4,
              'label'   => '会员列表',
              'en_name' => 'UserList',
              'route'   => '/user/userlist',
              'pid'     => 3,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 5,
              'label'   => '登录记录',
              'en_name' => 'LoginLog',
              'route'   => '/user/loginlog',
              'pid'     => 3,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 6,
              'label'   => '标签管理',
              'en_name' => 'TabManage',
              'route'   => '/user/tabmanage',
              'pid'     => 3,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 7,
              'label'   => '黑名单管理',
              'en_name' => 'BlackListManage',
              'route'   => '/user/blacklistmanage',
              'pid'     => 3,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 8,
              'label'   => '等级设置',
              'en_name' => 'LevelSetting',
              'route'   => '/user/levelsetting',
              'pid'     => 3,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 5,
              'type'    => 1,
             ],
             [
              'id'      => 9,
              'label'   => '洗码设置',
              'en_name' => 'WashSetting',
              'route'   => '/user/washsetting',
              'pid'     => 3,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 6,
              'type'    => 1,
             ],
             [
              'id'      => 10,
              'label'   => '财务管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'icon'    => 'iconmoneybag',
              'display' => 1,
              'level'   => 1,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 11,
              'label'   => '入款订单',
              'en_name' => 'IncomeOrder',
              'route'   => '/funds/incomeorder',
              'pid'     => 10,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 12,
              'label'   => '人工存取',
              'en_name' => 'ManualAccess',
              'route'   => '/funds/manualaccess',
              'pid'     => 10,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 13,
              'label'   => '出款审核',
              'en_name' => 'paymentreview',
              'route'   => '/funds/paymentreview',
              'pid'     => 10,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 14,
              'label'   => '出款订单',
              'en_name' => 'PaymentOrder',
              'route'   => '/funds/paymentorder',
              'pid'     => 10,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 15,
              'label'   => '资金帐变',
              'en_name' => 'FundChange',
              'route'   => '/funds/fundchange',
              'pid'     => 10,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 5,
              'type'    => 1,
             ],
             [
              'id'      => 16,
              'label'   => '公告管理',
              'en_name' => 'announce',
              'route'   => '#',
              'pid'     => 0,
              'icon'    => 'iconspeaker-5',
              'display' => 1,
              'level'   => 1,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 17,
              'label'   => '跑马灯消息',
              'en_name' => 'Marquee',
              'route'   => '/announce/marquee',
              'pid'     => 16,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 18,
              'label'   => '系统公告',
              'en_name' => 'SystemAnnounce',
              'route'   => '/announce/systemannounce',
              'pid'     => 16,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 19,
              'label'   => '登录弹窗公告',
              'en_name' => 'LoginPopup',
              'route'   => '/announce/loginpopup',
              'pid'     => 16,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 20,
              'label'   => '轮播公告',
              'en_name' => 'Carousel',
              'route'   => '/announce/carousel',
              'pid'     => 16,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 21,
              'label'   => '邮件系统',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'icon'    => 'icon185078emailmailstreamline',
              'display' => 1,
              'level'   => 1,
              'sort'    => 5,
              'type'    => 1,
             ],
             [
              'id'      => 22,
              'label'   => '发邮件',
              'en_name' => 'SendeMail',
              'route'   => '/email/sendemail',
              'pid'     => 21,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 23,
              'label'   => '收件箱',
              'en_name' => '',
              'route'   => '/email/receiveemail',
              'pid'     => 21,
              'icon'    => 'ReceiveEmail',
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 24,
              'label'   => '已发邮件',
              'en_name' => 'EmailSent',
              'route'   => '/email/emailsent',
              'pid'     => 21,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 25,
              'label'   => '短信推送',
              'en_name' => 'SmsPush',
              'route'   => '/email/smspush',
              'pid'     => 21,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 26,
              'label'   => '报表管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'icon'    => 'iconassistant_lefticon_Statisticalreportforms',
              'display' => 1,
              'level'   => 1,
              'sort'    => 6,
              'type'    => 1,
             ],
             [
              'id'      => 27,
              'label'   => '个人报表',
              'en_name' => 'PersonalReport',
              'route'   => '/report/personalreport',
              'pid'     => 26,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 28,
              'label'   => '游戏报表',
              'en_name' => 'GameReport',
              'route'   => '/report/gamereport',
              'pid'     => 26,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 29,
              'label'   => '公司报表',
              'en_name' => 'CompanyReport',
              'route'   => '/report/companyreport',
              'pid'     => 26,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 30,
              'label'   => '会员稽查',
              'en_name' => 'MemberAudit',
              'route'   => '/report/memberaudit',
              'pid'     => 26,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 31,
              'label'   => '平台注单',
              'en_name' => 'PlatformBet',
              'route'   => '/report/platformbet',
              'pid'     => 26,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 5,
              'type'    => 1,
             ],
             [
              'id'      => 32,
              'label'   => '活动报表',
              'en_name' => 'ActiveReport',
              'route'   => '/report/activereport',
              'pid'     => 26,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 6,
              'type'    => 1,
             ],
             [
              'id'      => 33,
              'label'   => '会员洗码',
              'en_name' => 'UserWash',
              'route'   => '/report/userwash',
              'pid'     => 26,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 7,
              'type'    => 1,
             ],
             [
              'id'      => 34,
              'label'   => '游戏管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'icon'    => 'iconicon4',
              'display' => 1,
              'level'   => 1,
              'sort'    => 7,
              'type'    => 1,
             ],
             [
              'id'      => 35,
              'label'   => 'H5游戏管理',
              'en_name' => 'GameH5',
              'route'   => '/game/gameh5',
              'pid'     => 34,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 36,
              'label'   => 'PC游戏管理',
              'en_name' => 'GamePC',
              'route'   => '/game/gamepc',
              'pid'     => 34,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 37,
              'label'   => 'APP游戏管理',
              'en_name' => 'GameApp',
              'route'   => '/game/gameapp',
              'pid'     => 34,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 38,
              'label'   => '平台管理',
              'en_name' => 'PlatForm',
              'route'   => '/game/platform',
              'pid'     => 34,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 39,
              'label'   => '分类管理',
              'en_name' => 'GameSort',
              'route'   => '/game/gamesort',
              'pid'     => 34,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 5,
              'type'    => 1,
             ],
             [
              'id'      => 40,
              'label'   => '活动管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'icon'    => 'iconhuodong',
              'display' => 1,
              'level'   => 1,
              'sort'    => 8,
              'type'    => 1,
             ],
             [
              'id'      => 41,
              'label'   => '静态活动',
              'en_name' => 'Static',
              'route'   => '/active/static',
              'pid'     => 40,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 42,
              'label'   => '动态活动',
              'en_name' => 'Dynamic',
              'route'   => '/active/dynamic',
              'pid'     => 40,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 43,
              'label'   => '金流管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'icon'    => 'icondingdangdaizijinliushui',
              'display' => 1,
              'level'   => 1,
              'sort'    => 9,
              'type'    => 1,
             ],
             [
              'id'      => 44,
              'label'   => '线下金流配置',
              'en_name' => 'OfflinePay',
              'route'   => '/pay/offlinepay',
              'pid'     => 43,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 45,
              'label'   => '线上金流配置',
              'en_name' => 'OnlinePay',
              'route'   => '/pay/onlinepay',
              'pid'     => 43,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 46,
              'label'   => '出款银行管理',
              'en_name' => 'ExportBank',
              'route'   => '/pay/exportbank',
              'pid'     => 43,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 47,
              'label'   => '设置管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'icon'    => 'iconshezhi2',
              'display' => 1,
              'level'   => 1,
              'sort'    => 11,
              'type'    => 1,
             ],
             [
              'id'      => 48,
              'label'   => '管理员分组',
              'en_name' => 'AdminSort',
              'route'   => '/set/adminsort',
              'pid'     => 47,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 49,
              'label'   => '全域设置',
              'en_name' => 'AllAreaSet',
              'route'   => '/set/allareaset',
              'pid'     => 47,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 50,
              'label'   => '客服设置',
              'en_name' => 'ServiceSet',
              'route'   => '/set/serviceset',
              'pid'     => 47,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 51,
              'label'   => '帮助设置',
              'en_name' => 'HelpSet',
              'route'   => '/set/helpset',
              'pid'     => 47,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 52,
              'label'   => '推广图片配置',
              'en_name' => 'PicConfig',
              'route'   => '/set/picconfig',
              'pid'     => 47,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 53,
              'label'   => '操作记录',
              'en_name' => 'OperatRecord',
              'route'   => '/set/operatrecord',
              'pid'     => 47,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 5,
              'type'    => 1,
             ],
             [
              'id'      => 54,
              'label'   => '银行卡反查中心',
              'en_name' => 'BankCenter',
              'route'   => '/set/bankcenter',
              'pid'     => 47,
              'icon'    => '',
              'display' => 1,
              'level'   => 2,
              'sort'    => 6,
              'type'    => 1,
             ],
             [
              'id'      => 55,
              'label'   => '系统设置',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'icon'    => '',
              'display' => 0,
              'level'   => 1,
              'sort'    => 12,
              'type'    => 1,
             ],
             [
              'id'      => 56,
              'label'   => '全域',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 55,
              'icon'    => '',
              'display' => 0,
              'level'   => 1,
              'sort'    => 12,
              'type'    => 1,
             ],
             [
              'id'      => 57,
              'label'   => '游戏回调',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 55,
              'icon'    => '',
              'display' => 0,
              'level'   => 1,
              'sort'    => 12,
              'type'    => 1,
             ],
             [
              'id'      => 58,
              'label'   => '顶部通知统计',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 55,
              'icon'    => '',
              'display' => 0,
              'level'   => 1,
              'sort'    => 12,
              'type'    => 1,
             ],
            ],
        );
    }
}
