<?php

use App\Models\Systems\SystemConfiguration;
use Illuminate\Database\Seeder;

/**
 * Class SystemConfigurationSeeder
 */
class SystemConfigurationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        SystemConfiguration::insert(
            [
             [
              'id'            => 1,
              'pid'           => 0,
              'platform_sign' => 'JHHY',
              'sign'          => null,
              'name'          => '系统配置',
              'value'         => null,
              'status'        => 1,
              'display'       => 0,
              'editable_type' => '',
             ],
             [
              'id'            => 2,
              'pid'           => 1,
              'platform_sign' => 'JHHY',
              'sign'          => 'is_crypt_data',
              'name'          => '传输数据是否加密',
              'value'         => 1,
              'status'        => 1,
              'display'       => 0,
              'editable_type' => '',
             ],
             [
              'id'            => 3,
              'pid'           => 0,
              'platform_sign' => 'JHHY',
              'sign'          => null,
              'name'          => '注册登录设定',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '',
             ],
             [
              'id'            => 4,
              'pid'           => 3,
              'platform_sign' => 'JHHY',
              'sign'          => 'login_error_num',
              'name'          => '登录密码错误限制次数',
              'value'         => 3,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 5,
              'pid'           => 3,
              'platform_sign' => 'JHHY',
              'sign'          => 'register_invite_code',
              'name'          => '注册邀请码',
              'value'         => 0,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '2',
             ],
             [
              'id'            => 6,
              'pid'           => 0,
              'platform_sign' => 'JHHY',
              'sign'          => null,
              'name'          => '游戏设定',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '',
             ],
             [
              'id'            => 7,
              'pid'           => 6,
              'platform_sign' => 'JHHY',
              'sign'          => 'system_maintenance',
              'name'          => '系统维护总开关',
              'value'         => 0,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '2',
             ],
             [
              'id'            => 8,
              'pid'           => 6,
              'platform_sign' => 'JHHY',
              'sign'          => 'commission',
              'name'          => '是否开启洗码',
              'value'         => 0,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '2',
             ],
             [
              'id'            => 9,
              'pid'           => 6,
              'platform_sign' => 'JHHY',
              'sign'          => 'chat_user_grade',
              'name'          => '聊天室用户等级',
              'value'         => 0,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '3',
             ],
             [
              'id'            => 10,
              'pid'           => 6,
              'platform_sign' => 'JHHY',
              'sign'          => 'play_min_recharge',
              'name'          => '最低充值多少才能游戏',
              'value'         => 30,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 11,
              'pid'           => 6,
              'platform_sign' => 'JHHY',
              'sign'          => 'withdraw_error_num',
              'name'          => '取款密码错误次数限制',
              'value'         => 3,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 12,
              'pid'           => 6,
              'platform_sign' => 'JHHY',
              'sign'          => 'popularize_url',
              'name'          => '推广分享地址',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 13,
              'pid'           => 6,
              'platform_sign' => 'JHHY',
              'sign'          => 'upload_url',
              'name'          => '下载地址域名',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 14,
              'pid'           => 6,
              'platform_sign' => 'JHHY',
              'sign'          => 'app_top_domain',
              'name'          => 'APP 大厅顶部域名配置',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 15,
              'pid'           => 6,
              'platform_sign' => 'JHHY',
              'sign'          => 'integral',
              'name'          => '输金额转换积分',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 16,
              'pid'           => 0,
              'platform_sign' => 'JHHY',
              'sign'          => null,
              'name'          => '活动金额限制设定',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '',
             ],
             [
              'id'            => 17,
              'pid'           => 16,
              'platform_sign' => 'JHHY',
              'sign'          => 'max_register_give',
              'name'          => '注册送活动最高金额限制',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1,2',
             ],
             [
              'id'            => 18,
              'pid'           => 16,
              'platform_sign' => 'JHHY',
              'sign'          => 'max_sign_in_give',
              'name'          => '签到活动最高金额限制',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1,2',
             ],
             [
              'id'            => 19,
              'pid'           => 16,
              'platform_sign' => 'JHHY',
              'sign'          => 'max_first_recharge_give',
              'name'          => '首充送活动最高金额限制',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1,2',
             ],
             [
              'id'            => 20,
              'pid'           => 16,
              'platform_sign' => 'JHHY',
              'sign'          => 'max_red_envelopes_give',
              'name'          => '抢红包最高金额限制',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1,2',
             ],
             [
              'id'            => 21,
              'pid'           => 16,
              'platform_sign' => 'JHHY',
              'sign'          => 'max_guess_give',
              'name'          => '有奖竞猜最高金额限制',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1,2',
             ],
             [
              'id'            => 22,
              'pid'           => 16,
              'platform_sign' => 'JHHY',
              'sign'          => 'max_roulette_give',
              'name'          => '转盘活动最高金额限制',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1,2',
             ],
             [
              'id'            => 23,
              'pid'           => 0,
              'platform_sign' => 'JHHY',
              'sign'          => null,
              'name'          => '出入款设定',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '',
             ],
             [
              'id'            => 24,
              'pid'           => 23,
              'platform_sign' => 'JHHY',
              'sign'          => 'withdraw_commission',
              'name'          => '出款手续费',
              'value'         => 2,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 25,
              'pid'           => 23,
              'platform_sign' => 'JHHY',
              'sign'          => 'withdraw_free_num',
              'name'          => '每天出款免手续费笔数',
              'value'         => 2,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 26,
              'pid'           => 23,
              'platform_sign' => 'JHHY',
              'sign'          => 'min_withdraw',
              'name'          => '每次出款最低金额',
              'value'         => 100,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 27,
              'pid'           => 23,
              'platform_sign' => 'JHHY',
              'sign'          => 'max_withdraw',
              'name'          => '每次出款最高金额',
              'value'         => 20000,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 28,
              'pid'           => 23,
              'platform_sign' => 'JHHY',
              'sign'          => 'day_withdraw',
              'name'          => '每日出款金额限制',
              'value'         => 100000,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 29,
              'pid'           => 23,
              'platform_sign' => 'JHHY',
              'sign'          => 'day_withdraw_num',
              'name'          => '每日出款次数',
              'value'         => 5,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 30,
              'pid'           => 23,
              'platform_sign' => 'JHHY',
              'sign'          => 'max_withdraw_commission',
              'name'          => '出款手续费最大金额',
              'value'         => 200,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 31,
              'pid'           => 23,
              'platform_sign' => 'JHHY',
              'sign'          => 'recharge_audit_times',
              'name'          => '入款稽核倍数',
              'value'         => 1,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 32,
              'pid'           => 23,
              'platform_sign' => 'JHHY',
              'sign'          => 'activity_audit_times',
              'name'          => '活动稽核倍数',
              'value'         => 2,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 33,
              'pid'           => 23,
              'platform_sign' => 'JHHY',
              'sign'          => 'audit_free',
              'name'          => '稽核不足出款手续费',
              'value'         => 0,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 34,
              'pid'           => 23,
              'platform_sign' => 'JHHY',
              'sign'          => 'audit_withdraw',
              'name'          => '稽核不足限制出款',
              'value'         => 1,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '2',
             ],
             [
              'id'            => 35,
              'pid'           => 23,
              'platform_sign' => 'JHHY',
              'sign'          => 'max_artificial_recharge',
              'name'          => '人工充值最高金额限制',
              'value'         => 500,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 36,
              'pid'           => 23,
              'platform_sign' => 'JHHY',
              'sign'          => 'bank_card_frozen',
              'name'          => '新绑银行卡多少小时能出款',
              'value'         => 2,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 37,
              'pid'           => 0,
              'platform_sign' => 'JHHY',
              'sign'          => null,
              'name'          => '返利配置',
              'value'         => null,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '',
             ],
             [
              'id'            => 38,
              'pid'           => 37,
              'platform_sign' => 'JHHY',
              'sign'          => 'rebate_percentage_1',
              'name'          => '一级返利',
              'value'         => 0,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 39,
              'pid'           => 37,
              'platform_sign' => 'JHHY',
              'sign'          => 'rebate_percentage_2',
              'name'          => '二级返利',
              'value'         => 0,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
             [
              'id'            => 40,
              'pid'           => 37,
              'platform_sign' => 'JHHY',
              'sign'          => 'rebate_percentage_3',
              'name'          => '三级返利',
              'value'         => 0,
              'status'        => 1,
              'display'       => 1,
              'editable_type' => '1',
             ],
            ],
        );
    }
}
