<?php

use App\Models\DeveloperUsage\Backend\SystemRoutesBackend;
use Illuminate\Database\Seeder;

/**
 * Class SystemRoutesBackendSeeder
 */
class SystemRoutesBackendSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        SystemRoutesBackend::insert(
            [
             [
              'route_name'    => 'headquarters-api.platform.assigned-games',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'assignedGames',
              'menu_group_id' => 4,
              'title'         => '厅主列表-游戏管理-已分配的游戏列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.unassigned-games',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'unassignedGames',
              'menu_group_id' => 4,
              'title'         => '厅主列表-游戏管理-未分配的游戏列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.get-search-data-of-assign-game',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'getSearchDataOfAssignGame',
              'menu_group_id' => 4,
              'title'         => '厅主列表-游戏管理-获取列表的查询数据',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.assign-games',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'assignGames',
              'menu_group_id' => 4,
              'title'         => '厅主列表-游戏管理-分配游戏',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.assigned-game-cancel',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'assignedGameCancel',
              'menu_group_id' => 4,
              'title'         => '厅主列表-游戏管理-移除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.detail',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'detail',
              'menu_group_id' => 4,
              'title'         => '厅主列表-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.do-add',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'doAdd',
              'menu_group_id' => 4,
              'title'         => '厅主列表-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.edit',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'edit',
              'menu_group_id' => 4,
              'title'         => '厅主列表-站点管理',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.skin-list',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'skinList',
              'menu_group_id' => 4,
              'title'         => '厅主列表-站点管理-皮肤列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.switch',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'switch',
              'menu_group_id' => 4,
              'title'         => '厅主列表-禁用启用',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.domain-detail',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'domainDetail',
              'menu_group_id' => 4,
              'title'         => '厅主列表-域名管理-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.domain-add',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'domainAdd',
              'menu_group_id' => 4,
              'title'         => '厅主列表-域名管理-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.domain-status',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'domainStatus',
              'menu_group_id' => 4,
              'title'         => '厅主列表-域名管理-修改状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.domain-delete',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'domainDelete',
              'menu_group_id' => 4,
              'title'         => '厅主列表-域名管理-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.maintain',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'maintain',
              'menu_group_id' => 4,
              'title'         => '厅主列表-维护',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.assign-activities',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'assignActivities',
              'menu_group_id' => 4,
              'title'         => '厅主列表-活动管理-分配活动',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.assigned-activities',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'assignedActivities',
              'menu_group_id' => 4,
              'title'         => '厅主列表-活动管理-已分配活动',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.unassign-activities',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'unassignActivities',
              'menu_group_id' => 4,
              'title'         => '厅主列表-活动管理-未分配活动',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.assigned-activity-cancel',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Merchant\PlatformController',
              'method'        => 'assignedActivityCancel',
              'menu_group_id' => 4,
              'title'         => '厅主列表-活动管理-移除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.login-log.index',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Setting\LoginLogController',
              'method'        => 'index',
              'menu_group_id' => 5,
              'title'         => '登录日志-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.opt-index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameVendorController',
              'method'        => 'indexDo',
              'menu_group_id' => 7,
              'title'         => '游戏管理-厂商管理-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.opt-add-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameVendorController',
              'method'        => 'addDo',
              'menu_group_id' => 7,
              'title'         => '游戏管理-游戏厂商-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.opt-edit-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameVendorController',
              'method'        => 'editDo',
              'menu_group_id' => 7,
              'title'         => '游戏管理-游戏厂商-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.opt-index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameVendorController',
              'method'        => 'indexDo',
              'menu_group_id' => 7,
              'title'         => '游戏管理-游戏厂商-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.opt-del-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameVendorController',
              'method'        => 'delDo',
              'menu_group_id' => 7,
              'title'         => '游戏管理-游戏厂商-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.opt-status-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameVendorController',
              'method'        => 'statusDo',
              'menu_group_id' => 7,
              'title'         => '游戏管理-游戏厂商-改变状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.icon',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameVendorController',
              'method'        => 'icon',
              'menu_group_id' => 7,
              'title'         => '游戏管理-游戏厂商-更新厂商icon',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.opt-status-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameTypeController',
              'method'        => 'statusDo',
              'menu_group_id' => 8,
              'title'         => '游戏管理-分类设置-改变状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.opt-index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameTypeController',
              'method'        => 'indexDo',
              'menu_group_id' => 8,
              'title'         => '游戏管理-分类设置-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.add-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameTypeController',
              'method'        => 'addDo',
              'menu_group_id' => 8,
              'title'         => '游戏管理-分类设置-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.edit-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameTypeController',
              'method'        => 'editDo',
              'menu_group_id' => 8,
              'title'         => '游戏管理-分类设置-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameTypeController',
              'method'        => 'indexDo',
              'menu_group_id' => 8,
              'title'         => '游戏管理-分类设置-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.del-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameTypeController',
              'method'        => 'delDo',
              'menu_group_id' => 8,
              'title'         => '游戏管理-分类设置-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.status-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameTypeController',
              'method'        => 'statusDo',
              'menu_group_id' => 8,
              'title'         => '游戏管理-分类设置-改变状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.opt-status-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameController',
              'method'        => 'statusDo',
              'menu_group_id' => 9,
              'title'         => '游戏管理-游戏管理-改变状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.opt-index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameController',
              'method'        => 'indexDo',
              'menu_group_id' => 9,
              'title'         => '游戏管理-游戏管理-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.edit-detail',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameController',
              'method'        => 'editDetail',
              'menu_group_id' => 9,
              'title'         => '游戏管理-游戏管理-编辑详情',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.activity.status-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Activity\BackendSystemDynActivityController',
              'method'        => 'status',
              'menu_group_id' => 11,
              'title'         => '活动管理-活动列表-改变状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.activity.index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Activity\BackendSystemDynActivityController',
              'method'        => 'index',
              'menu_group_id' => 11,
              'title'         => '活动管理-活动列表-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.email.send',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Email\BackendSystemEmailController',
              'method'        => 'send',
              'menu_group_id' => 13,
              'title'         => '邮件系统-发邮件-发送邮件',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.email.recent-contact',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Email\BackendSystemEmailController',
              'method'        => 'recentContact',
              'menu_group_id' => 13,
              'title'         => '邮件系统-发邮件-最近联系人',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.email.contact',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Email\BackendSystemEmailController',
              'method'        => 'contact',
              'menu_group_id' => 13,
              'title'         => '邮件系统-发邮件-联系人',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.email.received-index',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Email\BackendSystemEmailController',
              'method'        => 'receivedIndex',
              'menu_group_id' => 14,
              'title'         => '邮件系统-收邮件-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.email.read-email',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Email\BackendSystemEmailController',
              'method'        => 'readEmail',
              'menu_group_id' => 14,
              'title'         => '邮件系统-收邮件-读邮件',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.email.send-index',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Email\BackendSystemEmailController',
              'method'        => 'sendIndex',
              'menu_group_id' => 15,
              'title'         => '邮件系统-已发邮件-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.opt-index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceVendorController',
              'method'        => 'indexDo',
              'menu_group_id' => 22,
              'title'         => '金流配置-厂商管理-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.opt-status-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceVendorController',
              'method'        => 'statusDo',
              'menu_group_id' => 22,
              'title'         => '金流配置-厂商管理-改变状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.opt-index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceTypeController',
              'method'        => 'indexDo',
              'menu_group_id' => 23,
              'title'         => '金流配置-分类管理-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.opt-status-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceTypeController',
              'method'        => 'statusDo',
              'menu_group_id' => 23,
              'title'         => '金流配置-分类管理-改变状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.opt-status-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceChannelController',
              'method'        => 'statusDo',
              'menu_group_id' => 24,
              'title'         => '金流配置-通道管理-改变状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.opt-index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceChannelController',
              'method'        => 'indexDo',
              'menu_group_id' => 24,
              'title'         => '金流配置-通道管理-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.opt-edit-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceChannelController',
              'method'        => 'optEditDo',
              'menu_group_id' => 24,
              'title'         => '金流配置-通道管理-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.edit-detail',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceChannelController',
              'method'        => 'editDetail',
              'menu_group_id' => 24,
              'title'         => '金流配置-通道管理-编辑详情',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.backend-admin-group.detail',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Setting\AdminController',
              'method'        => 'groupList',
              'menu_group_id' => 26,
              'title'         => '管理员分组-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.backend-admin-group.create',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Setting\AdminController',
              'method'        => 'groupCreate',
              'menu_group_id' => 26,
              'title'         => '管理员分组-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.backend-admin-group.edit',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Setting\AdminController',
              'method'        => 'groupEdit',
              'menu_group_id' => 26,
              'title'         => '管理员分组-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.backend-admin-group.delete-access-group',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Setting\AdminController',
              'method'        => 'groupDestroy',
              'menu_group_id' => 26,
              'title'         => '管理员分组-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.backend-admin-group.specific-group-users',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Setting\AdminController',
              'method'        => 'specificGroupUsers',
              'menu_group_id' => 26,
              'title'         => '管理员分组-管理员列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.create',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Admin\BackendAdminUserController',
              'method'        => 'create',
              'menu_group_id' => 26,
              'title'         => '总后台管理员-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.update-admin-group',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Admin\BackendAdminUserController',
              'method'        => 'updateAdminGroup',
              'menu_group_id' => 26,
              'title'         => '总后台管理员-修改所属组',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.delete-admin',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Admin\BackendAdminUserController',
              'method'        => 'deleteAdmin',
              'menu_group_id' => 26,
              'title'         => '总后台管理员-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.update-password',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Admin\BackendAdminUserController',
              'method'        => 'updatePassword',
              'menu_group_id' => 26,
              'title'         => '总后台管理员-修改其他管理员密码',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.self-update-password',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Admin\BackendAdminUserController',
              'method'        => 'selfUpdatePassword',
              'menu_group_id' => 26,
              'title'         => '总后台管理员-管理员自己修改密码',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.search-admin',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Admin\BackendAdminUserController',
              'method'        => 'searchAdmin',
              'menu_group_id' => 26,
              'title'         => '总后台管理员-搜索管理员',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.switch-admin',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Admin\BackendAdminUserController',
              'method'        => 'switchAdmin',
              'menu_group_id' => 26,
              'title'         => '总后台管理员-禁用启用',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.operation-log.index',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Setting\OperationLogController',
              'method'        => 'index',
              'menu_group_id' => 27,
              'title'         => '操作日志-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.sms-config.index',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Setting\SmsConfigController',
              'method'        => 'index',
              'menu_group_id' => 28,
              'title'         => '短信配置-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.sms-config.do-add',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Setting\SmsConfigController',
              'method'        => 'doAdd',
              'menu_group_id' => 28,
              'title'         => '短信配置-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.sms-config.edit',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Setting\SmsConfigController',
              'method'        => 'edit',
              'menu_group_id' => 28,
              'title'         => '短信配置-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.sms-config.delete',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Setting\SmsConfigController',
              'method'        => 'delete',
              'menu_group_id' => 28,
              'title'         => '短信配置-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.sms-config.status',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Setting\SmsConfigController',
              'method'        => 'status',
              'menu_group_id' => 28,
              'title'         => '短信配置-禁用启用',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.add',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Backend\MenuController',
              'method'        => 'doAdd',
              'menu_group_id' => 30,
              'title'         => '总后台菜单-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.delete',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Backend\MenuController',
              'method'        => 'delete',
              'menu_group_id' => 30,
              'title'         => '总后台菜单-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.edit',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Backend\MenuController',
              'method'        => 'edit',
              'menu_group_id' => 30,
              'title'         => '总后台菜单-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.change-parent',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Backend\MenuController',
              'method'        => 'changeParent',
              'menu_group_id' => 30,
              'title'         => '总后台菜单-修改上级',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.display',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Backend\MenuController',
              'method'        => 'display',
              'menu_group_id' => 30,
              'title'         => '总后台菜单-是否显示',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-route.index',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Backend\RouteController',
              'method'        => 'index',
              'menu_group_id' => 30,
              'title'         => '总后台路由-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-route.do-add',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Backend\RouteController',
              'method'        => 'doAdd',
              'menu_group_id' => 30,
              'title'         => '总后台路由-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-route.edit',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Backend\RouteController',
              'method'        => 'edit',
              'menu_group_id' => 30,
              'title'         => '总后台路由-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-route.delete',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Backend\RouteController',
              'method'        => 'delete',
              'menu_group_id' => 30,
              'title'         => '总后台路由-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-route.is-open',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Backend\RouteController',
              'method'        => 'isOpen',
              'menu_group_id' => 30,
              'title'         => '总后台路由-是否开放',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-menu.get-all-menu',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Merchant\MenuController',
              'method'        => 'getAllMenu',
              'menu_group_id' => 31,
              'title'         => '代理后台菜单-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-menu.add',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Merchant\MenuController',
              'method'        => 'doAdd',
              'menu_group_id' => 31,
              'title'         => '代理后台菜单-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-menu.edit',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Merchant\MenuController',
              'method'        => 'edit',
              'menu_group_id' => 31,
              'title'         => '代理后台菜单-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-menu.delete',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Merchant\MenuController',
              'method'        => 'delete',
              'menu_group_id' => 31,
              'title'         => '代理后台菜单-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-menu.change-parent',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Merchant\MenuController',
              'method'        => 'changeParent',
              'menu_group_id' => 31,
              'title'         => '代理后台菜单-修改上级',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-menu.display',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Merchant\MenuController',
              'method'        => 'display',
              'menu_group_id' => 31,
              'title'         => '代理后台菜单-是否显示',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-route.index',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Merchant\RouteController',
              'method'        => 'index',
              'menu_group_id' => 31,
              'title'         => '代理后台路由-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-route.do-add',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Merchant\RouteController',
              'method'        => 'doAdd',
              'menu_group_id' => 31,
              'title'         => '代理后台路由-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-route.edit',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Merchant\RouteController',
              'method'        => 'edit',
              'menu_group_id' => 31,
              'title'         => '代理后台路由-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-route.delete',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Merchant\RouteController',
              'method'        => 'delete',
              'menu_group_id' => 31,
              'title'         => '代理后台路由-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-route.is-open',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Merchant\RouteController',
              'method'        => 'isOpen',
              'menu_group_id' => 31,
              'title'         => '代理后台路由-是否开放',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.schedule.index',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\ScheduleController',
              'method'        => 'index',
              'menu_group_id' => 32,
              'title'         => '定时任务-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.schedule.do-add',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\ScheduleController',
              'method'        => 'doAdd',
              'menu_group_id' => 32,
              'title'         => '定时任务-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.schedule.edit',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\ScheduleController',
              'method'        => 'edit',
              'menu_group_id' => 32,
              'title'         => '定时任务-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.schedule.delete',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\ScheduleController',
              'method'        => 'delete',
              'menu_group_id' => 32,
              'title'         => '定时任务-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.add-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameController',
              'method'        => 'addDo',
              'menu_group_id' => 34,
              'title'         => '开发管理-游戏管理-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.edit-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameController',
              'method'        => 'editDo',
              'menu_group_id' => 34,
              'title'         => '开发管理-游戏管理-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameController',
              'method'        => 'indexDo',
              'menu_group_id' => 34,
              'title'         => '开发管理-游戏管理-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.del-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameController',
              'method'        => 'delDo',
              'menu_group_id' => 34,
              'title'         => '开发管理-游戏管理-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.get-search-condition',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameController',
              'method'        => 'getSearchCondition',
              'menu_group_id' => 34,
              'title'         => '开发管理-游戏管理-获取游戏列表的查询条件',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.status-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameController',
              'method'        => 'statusDo',
              'menu_group_id' => 34,
              'title'         => '开发管理-游戏管理-改变状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.icon',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Game\BackendGameController',
              'method'        => 'icon',
              'menu_group_id' => 34,
              'title'         => '开发管理-游戏管理-更新游戏图标',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.add-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceVendorController',
              'method'        => 'addDo',
              'menu_group_id' => 35,
              'title'         => '开发管理-金流厂商-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.edit-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceVendorController',
              'method'        => 'editDo',
              'menu_group_id' => 35,
              'title'         => '开发管理-金流厂商-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceVendorController',
              'method'        => 'indexDo',
              'menu_group_id' => 35,
              'title'         => '开发管理-金流厂商-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.del-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceVendorController',
              'method'        => 'delDo',
              'menu_group_id' => 35,
              'title'         => '开发管理-金流厂商-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.status-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceVendorController',
              'method'        => 'statusDo',
              'menu_group_id' => 35,
              'title'         => '开发管理-金流厂商-改变状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.add-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceTypeController',
              'method'        => 'addDo',
              'menu_group_id' => 36,
              'title'         => '开发管理-金流分类-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.edit-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceTypeController',
              'method'        => 'editDo',
              'menu_group_id' => 36,
              'title'         => '开发管理-金流分类-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceTypeController',
              'method'        => 'indexDo',
              'menu_group_id' => 36,
              'title'         => '开发管理-金流分类-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.del-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceTypeController',
              'method'        => 'delDo',
              'menu_group_id' => 36,
              'title'         => '开发管理-金流分类-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.status-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceTypeController',
              'method'        => 'statusDo',
              'menu_group_id' => 36,
              'title'         => '开发管理-金流分类-改变状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.add-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceChannelController',
              'method'        => 'addDo',
              'menu_group_id' => 37,
              'title'         => '开发管理-金流通道-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.edit-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceChannelController',
              'method'        => 'editDo',
              'menu_group_id' => 37,
              'title'         => '开发管理-金流通道-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceChannelController',
              'method'        => 'indexDo',
              'menu_group_id' => 37,
              'title'         => '开发管理-金流通道-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.del-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceChannelController',
              'method'        => 'delDo',
              'menu_group_id' => 37,
              'title'         => '开发管理-金流通道-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.get-search-condition',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceChannelController',
              'method'        => 'getSearchCondition',
              'menu_group_id' => 37,
              'title'         => '开发管理-金流通道-获取金流通道列表的查询条件',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.status-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Finance\BackendFinanceChannelController',
              'method'        => 'statusDo',
              'menu_group_id' => 37,
              'title'         => '开发管理-金流通道-改变状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.bank.add-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\BackendSystemBankController',
              'method'        => 'addDo',
              'menu_group_id' => 38,
              'title'         => '开发管理-银行卡配置-添加',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.bank.edit-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\BackendSystemBankController',
              'method'        => 'edit',
              'menu_group_id' => 38,
              'title'         => '开发管理-银行卡配置-编辑',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.bank.index-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\BackendSystemBankController',
              'method'        => 'index',
              'menu_group_id' => 38,
              'title'         => '开发管理-银行卡配置-列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.bank.del-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\BackendSystemBankController',
              'method'        => 'delDo',
              'menu_group_id' => 38,
              'title'         => '开发管理-银行卡配置-删除',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.bank.status-do',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\BackendSystemBankController',
              'method'        => 'status',
              'menu_group_id' => 38,
              'title'         => '开发管理-银行卡配置-改变状态',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.login',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\BackendAuthController',
              'method'        => 'login',
              'menu_group_id' => 39,
              'title'         => '登录',
              'description'   => null,
              'is_open'       => 1,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.logout',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\BackendAuthController',
              'method'        => 'logout',
              'menu_group_id' => 39,
              'title'         => '登出',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.get-all-menu',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Backend\MenuController',
              'method'        => 'getAllMenu',
              'menu_group_id' => 39,
              'title'         => '总后台所有菜单列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.current-admin-menu',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Backend\MenuController',
              'method'        => 'currentAdminMenu',
              'menu_group_id' => 39,
              'title'         => '当前管理员拥有的菜单列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.all-require-infos',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\DeveloperUsage\Backend\MenuController',
              'method'        => 'allRequireInfos',
              'menu_group_id' => 39,
              'title'         => '添加编辑路由时获取的可用路由列表',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.sortable.update-sortable',
              'controller'    => 'App\Http\Controllers\CommonApi\SortableController',
              'method'        => 'updateSortable',
              'menu_group_id' => 39,
              'title'         => 'Sortable-拖拽排序',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 0,
             ],
             [
              'route_name'    => 'headquarters-api.uploads.images',
              'controller'    => 'App\Http\Controllers\BackendApi\Headquarters\Upload',
              'method'        => 'upload',
              'menu_group_id' => 39,
              'title'         => '上传图片',
              'description'   => null,
              'is_open'       => 0,
              'is_ack'        => 1,
             ],
            ],
        );
    }
}
